leadliner/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
import datetime

from leadliner import db
from leadliner.forms import SignUpForm
from leadliner.forms import UserLoginForm
from leadliner.models import UserData

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/landing')
def landing():
    current_app.logger.info('non-member, auth/landing, view')
    return render_template('landing.html')

@bp.route('/signup', methods=('GET', 'POST'))
def signup():
    current_app.logger.info('non-member, auth/signup, view')
    form = SignUpForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = UserData.query.filter_by(email=form.email.data).first()
        if not user:
            user = UserData(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        join_date=datetime.datetime.now(),)
            db.session.add(user)
            db.session.commit()
            session['user_id'] = user.id
            return redirect(url_for('onboarding.keywords_select'))
        else:
            flash('이미 존재하는 계정입니다.')
    return render_template('signup.html', form=form)


@bp.route('/policy', methods=('GET', 'POST'))
def signup_policy():
    return render_template('policy.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    current_app.logger.info('non-member, auth/login, view')
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = UserData.query.filter_by(email=form.email.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.home'))
        flash(error)
    return render_template('login.html', form=form)

leadliner/views/main_views.py
from flask import Blueprint
from flask import Blueprint, render_template, session, redirect, url_for, jsonify, current_app, request
from leadliner.MakeUserNews import MakeUserNews
from leadliner.GetStockPrice import GetStockPrice
import pandas as pd
import io
from leadliner import db
from datetime import datetime, timedelta

from leadliner.models import UserData, KeywordData, KeywordNewsData

bp = Blueprint('main', __name__, url_prefix='/')

def get_stock_info(stock, get_stock_price):
    data = {
        'name': 'name', 
        'price': 0.00,
        'rate': 0.00
    }

    if stock.korea_stock:
        data['name'] = stock.ko_name
        naver_url = f"https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query={stock.ko_name}"
        data['naver_news_link'] = naver_url
        price, rate = get_stock_price.korea_stock_price(stock.stock_code)
        data['price'] = f"{price}원"
        data['rate'] = format(float(rate), ".2f")
    else:
        if stock.ko_name:
            data['name'] = stock.ko_name
            data['naver_news_link'] = f"https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query={stock.ko_name}"
        else:
            data['name'] = stock.en_name
        
        data['reuters_news_link'] = f"https://www.reuters.com/site-search/?query={stock.en_name}"
        data['cnbc_news_link'] = f"https://www.cnbc.com/search/?query={stock.en_name}"
        data['yahoo_news_link'] = f"https://finance.yahoo.com/quote/{stock.stock_code}/news/"
        price, rate = get_stock_price.usa_stock_price(stock.stock_code)
        data['price'] = f"{format(float(price or 0), '.2f')}달러"
        data['rate'] = format(float(rate or 0), ".2f")

    return data

def get_news_data(keyword):
    # 현재 시간
    current_time = datetime.now()
    
    # KeywordNewsData에서 해당 키워드의 데이터 조회
    news_data = KeywordNewsData.query.filter_by(keyword=keyword).first()
    
    if news_data is None:
        # 데이터가 없는 경우, 새로운 데이터 생성
        make_user_news = MakeUserNews()
        news = make_user_news.make_user_news(keyword)
        new_data = KeywordNewsData(
            keyword=keyword,
            last_update=current_time,
            news1 = news[0],
            news2 = news[1],
            news3 = news[2]
        )
        db.session.add(new_data)
        db.session.commit()
        return [news[0], news[1], news[2]] 
    
    elif current_time - news_data.last_update > timedelta(hours=1):
        make_user_news = MakeUserNews()
        news = make_user_news.make_user_news(keyword)
        news_data.news1 = news[0]
        news_data.news2 = news[1]
        news_data.news3 = news[2]
        news_data.last_update = current_time
        db.session.commit()
        return [news[0], news[1], news[2]] 
    
    else:
        
        news = [news_data.news1, news_data.news2, news_data.news3]
        return news


@bp.route('/')
def home():
    user_id = session.get('user_id')

    if not user_id:
        return redirect(url_for('auth.landing'))  # Redirect to signup if no user_id in session
    user = UserData.query.get(user_id)
    if not user:
        session.pop('user_id', None)
        return redirect(url_for('auth.landing'))
    
    #홈화면 뷰 로깅
    current_app.logger.info(f'user{user_id}, main/home, view')

    user_keyword_data = user.keyword_list
    if not user_keyword_data:
       return render_template("home.html", nickname=user.username)
    
    code_list = user_keyword_data.split(', ')
    
    stock_list = [] #주식 객체
    keyword_list = [] #주식 이름

    for code in code_list:
        stock = KeywordData.query.filter_by(stock_code=code).first()
        stock_list.append(stock)
        if stock.ko_name:
            keyword_list.append(stock.ko_name)
        else:
            keyword_list.append(stock.en_name)

    get_stock_price = GetStockPrice()
    news_data = [get_stock_info(stock, get_stock_price) for stock in stock_list]

    # for data in news_data:
    #     data['news'] = get_news_data(data['name'])

    return render_template('home.html', nickname=user.username, news_data=news_data, keyword_list=keyword_list)

@bp.route('/get_news_data', methods=['POST'])
def get_news_data_route():
    keyword = request.json['keyword']
    news = get_news_data(keyword)
    return jsonify(news)


@bp.route('/log_click', methods=['POST'])
def log_click():
    user_id = session.get('user_id')
    if not user_id:
        return jsonify({"error": "User not logged in"}), 401

    # 로그 기록
    current_app.logger.info(f'user{user_id}, main/home, link_click')

    return jsonify({"status": "success"}), 200

@bp.route('/logout')
def logout():
    user_id = session.get('user_id')
    session.clear()
    #로그아웃 로깅
    current_app.logger.info(f'user{user_id}, main/logout, logout')
    return redirect(url_for('main.home'))

leadliner/views/mypage_views.py
from flask import Blueprint
from flask import Blueprint, render_template, session, redirect, url_for, jsonify, request, flash, current_app
from functools import wraps

from leadliner import db
from leadliner.forms import AccountInfoForm
from leadliner.models import UserData, KeywordData, TopKeywordData

bp = Blueprint('mypage', __name__, url_prefix='/mypage')


@bp.route('/account', methods=('GET', 'POST'))
def my_account():
    user_id = session.get('user_id')

    if not user_id:
        return redirect(url_for('main.home'))  # Redirect to signup if no user_id in session
    user = UserData.query.get(user_id)
    if not user:
        session.pop('user_id', None)
        return redirect(url_for('main.home'))
    
    #계정 정보 페이지 뷰 로깅
    current_app.logger.info(f'user{user_id}, mypage/account, view')
    form = AccountInfoForm()
    mailing_list = user.mailing_list
    
    if request.method == 'POST' and form.validate_on_submit():
        user_check = UserData.query.filter_by(email=form.email.data).first()
        
        if (not user_check) or (user_check.email == user.email):
            try:
                user.username = form.username.data
                user.email = form.email.data
                if form.mailing_list.data:
                    user.mailing_list = form.mailing_list.data
                else:
                    user.mailing_list = False
                db.session.commit()
                session['user_id'] = user.id
                return redirect(url_for('main.home'))
            except Exception as e:
                db.session.rollback()
                return jsonify(success=False, message=str(e)), 500
        else:
            flash('다른 계정에 가입한 이메일 주소입니다.')

    return render_template('mypage_account.html', nickname=user.username, email=user.email, form=form, mailing_list=mailing_list)

@bp.route('/logout')
def logout():
    user_id = session.get('user_id')
    session.clear()
    #계정 정보 페이지 로그아웃 로깅
    current_app.logger.info(f'user{user_id}, mypage/account, logout')
    return redirect(url_for('main.home'))

@bp.route('/withdraw', methods=['POST'])
def withdraw():
    user_id = session.get('user_id')
    if not user_id:
        return jsonify(success=False, message="User not authenticated"), 401

    user = UserData.query.get(user_id)
    if not user:
        return jsonify(success=False, message="User not found"), 404

    try:
        db.session.delete(user)
        db.session.commit()

        # 세션 클리어
        session.clear()
        current_app.logger.info(f'user{user_id}, mypage/account, withdraw')
        return jsonify(success=True, redirect_url=url_for('auth.landing'))
    
    except Exception as e:
        current_app.logger.error(f"Error occurred: {str(e)}")
        db.session.rollback()
        return jsonify(success=False, message=str(e)), 500


#키워드 편집 페이지

@bp.route('/keyword')
def my_keyword():
    user_id = session.get('user_id')

    if not user_id:
        return redirect(url_for('main.home'))  # Redirect to signup if no user_id in session
    user = UserData.query.get(user_id)
    if not user:
        session.pop('user_id', None)
        return redirect(url_for('main.home'))
    
    #키워드 편집 페이지 로깅
    current_app.logger.info(f'user{user_id}, mypage/keyword, view')
    
    user_keyword_data = user.keyword_list
    keyword_list = []
    if user_keyword_data:
        user_keyword_list = user_keyword_data.split(', ')
        for keyword in user_keyword_list:
            stock = KeywordData.query.filter_by(stock_code=keyword).first()
            if stock.ko_name:
                keyword_list.append(stock.ko_name)
            else:
                keyword_list.append(stock.en_name)


    pre_set_keyword_data = [keyword.ko_name for keyword in TopKeywordData.query.all()]
    pre_set_keyword_data = [x for x in pre_set_keyword_data if x not in keyword_list]

    ko_keywords = [keyword.ko_name for keyword in KeywordData.query.filter_by(korea_stock=True).all()]
    en_keywords = [keyword.en_name for keyword in KeywordData.query.filter_by(korea_stock=False).all()]
    all_keywords = ko_keywords + en_keywords

    mailing_list = user.mailing_list

    return render_template('mypage_keyword.html', user_keywords=keyword_list, top_keywords=pre_set_keyword_data, all_keywords=all_keywords ,mailing_list = mailing_list)

@bp.route('/save-keywords', methods=['POST'])
def submit_keywords():
    user_id = session.get('user_id')
    if not user_id:
        return jsonify(success=False, message="User not authenticated"), 401
    data = request.get_json()
    keywords = data.get('keywords', [])
    agreement = data.get('agreement', False)

    user = UserData.query.get(user_id)
    codes = []
    for keyword in keywords:
        stock = KeywordData.query.filter_by(ko_name=keyword).first()
        if stock:
            codes.append(stock.stock_code)
        else:
            stock = KeywordData.query.filter_by(en_name=keyword).first()
            if stock:
                codes.append(stock.stock_code)
            else:
                continue

    user.keyword_list = ', '.join(codes)
    if agreement:
        user.mailing_list = agreement

    try:
        db.session.commit()
        return jsonify(success=True, redirect_url=url_for('main.home'))
    except Exception as e:
        db.session.rollback()
        return jsonify(success=False, message=str(e)), 500

leadliner/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <ul style="list-style-type: none; padding-left: 0;">
        {% for error in errors %}
        <li style="color: red; font-weight: bold;">{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert" style="color: red; font-weight: bold; ">
    {{ message }}
</div>
{% endfor %}

leadliner/templates/home.html
<html lang="ko">
<head>
    <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5Z4CN57J');</script>
    <!-- End Google Tag Manager -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keyword" content="맞춤 뉴스, 개인화 뉴스, 뉴스 추천, 뉴스 큐레이션, 주식 뉴스, 경제 뉴스, 테크 뉴스">
    <meta name="description" content="내 보유 주식 뉴스만 모아보고 싶다면? 관심 있는 키워드만 선택하면 관련 뉴스만 쏙쏙! 시간 낭비 없는 개인화 맞춤 뉴스 서비스, 리드라이너에서 시작하세요.">
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4CJFS0TXDQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4CJFS0TXDQ');
</script>
    <title>리드라이너 - 나만의 주식 뉴스 브리핑</title>
    <link rel="stylesheet" href="../static/css/home_style.css">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5Z4CN57J"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <header>
        <img src="../static/assets/logo(black).png" alt="Leadliner 로고">
        <div class="dropdown">
            <button class="mypage-button" onclick="toggleDropdown()">mypage</button>
            <div id="myDropdown" class="dropdown-content">
                <a href="{{url_for('mypage.my_account')}}" class="secure-link">계정</a>
                <a href="{{url_for('mypage.my_keyword')}}" class="secure-link">키워드 편집</a>
                <a href="{{url_for('main.logout')}}">로그아웃</a>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="news-area">
            <h1>{{nickname}}님의 주식 뉴스 페이지</h1>

            {% for news in news_data %}
            <div class="stock-news">
                <section class="stock-info">
                    <div class="stock-item">
                        <span class="stock-name">{{news['name']}}</span>
                        <span class="stock-price-info">
                            <span class="stock-price">{{news['price']}}</span>
                            {% if news['rate'][0]=='-' %}
                            <span class="stock-change negative">{{news['rate']}}%</span>
                            {% else %}
                            <span class="stock-change positive">+{{news['rate']}}%</span>
                            {% endif %}
                        </span>
                    </div>
                </section>
                <section class="news-summary">
                    <h2>뉴스 요약</h2>
                    <p><span class="news-bullet">&#9670;</span>AI가 요약한 오늘의 <b>{{news['name']}}</b> 뉴스입니다.</p>
                    <div class="news-summary-item">
                        <div class="loading">
                            <span class="loading-icon">&#9670;</span>
                            <span class="loading-text">
                                <span>A</span><span>I</span><span>가</span>
                                <span>오</span><span>늘</span><span>의</span>
                                <span>뉴</span><span>스</span><span>를</span>
                                <span>요</span><span>약</span><span>하</span><span>고</span>
                                <span>있</span><span>습</span><span>니</span><span>다</span>
                            </span>
                        </div>
                    </div>
                </section>
                <section class="news-links">
                    <h4>뉴스 직접 보기</h4>
                    <div class="news-sources">
                        {% if news['naver_news_link'] %}
                        <a href="{{news['naver_news_link']}}" class="news-source-btn naver">네이버 뉴스</a>
                        {% endif %}
                        {% if news['reuters_news_link'] %}
                        <a href="{{news['reuters_news_link']}}" class="news-source-btn reuters">Reuters</a>
                        <a href="{{news['cnbc_news_link']}}" class="news-source-btn cnbc">CNBC</a>
                        <a href="{{news['yahoo_news_link']}}" class="news-source-btn yahoo">Yahoo Finance</a>
                        {% endif %}
                    </div>

                </section>

            </div>
            {% endfor %}
        </div>

        <aside class="sidebar">
            <h2>키워드</h2>
            <ul id="keyword-list">
                {% for keyword in keyword_list %}
                    <li class="keyword-item" data-keyword="{{keyword}}">{{keyword}}</li>
                {% endfor %}
            </ul>
            <a href="https://forms.gle/TiDdZ9MbpBaC7tQ79">
                <p class="contact-info">
                    <small>
                        문의하기
                    </small>
                </p>
            </a>
            <p class="investor-info">
                <small>
                    *화면에 표시된 시세는 실제 시세와 시간 차이가 있을 수 있습니다. 
                </small>
            </p>
        </aside>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        function toggleDropdown() {
            document.getElementById("myDropdown").classList.toggle("show");
        }
        // 드롭다운 메뉴 외부를 클릭하면 메뉴가 닫히도록 설정
        window.onclick = function(event) {
            if (!event.target.matches('.mypage-button')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }  

        $(document).ready(function() {
    const csrfToken = $('meta[name="csrf-token"]').attr('content');

    function loadNewsData() {
        $('.stock-news').each(function() {
            var $this = $(this);
            var keyword = $this.find('.stock-item .stock-name').text().trim();
            var $newsSummary = $this.find('.news-summary-item');

            $.ajax({
                url: '/get_news_data',
                method: 'POST',
                contentType: 'application/json',
                headers: {
                    'X-CSRFToken': csrfToken
                },
                data: JSON.stringify({ keyword: keyword }),
                success: function(data) {
                    console.log('Received data:', data);  // 데이터 로깅
                    if (Array.isArray(data) && data.length === 3) {
                        $newsSummary.empty(); // 기존 내용 삭제
                        typeWriterSequence($newsSummary, data, 0);
                    } else {
                        $newsSummary.html('<p>뉴스 데이터 형식이 올바르지 않습니다.</p>');
                    }
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.error('AJAX error:', textStatus, errorThrown);  // 오류 로깅
                    $newsSummary.html('<p>뉴스를 불러오는 데 실패했습니다.</p>');
                }
            });
        });
    }
    
    function typeWriterSequence($container, dataArray, index) {
    if (index < dataArray.length) {
        var $p = $('<p>').addClass('typing-effect').appendTo($container);
        typeWriter($p, dataArray[index], 0, function() {
            setTimeout(function() {
                typeWriterSequence($container, dataArray, index + 1);
            }, 250); // 다음 문장으로 넘어가기 전 대기
        });
    }
}

    function typeWriter($element, text, i, callback) {
    if (i < text.length) {
        $element.text($element.text() + text.charAt(i));
        setTimeout(function() {
            typeWriter($element, text, i + 1, callback);
        }, Math.random() * 20 + 20); //  랜덤한 간격으로 타이핑
    } else {
        $element.removeClass('typing-effect');
        if (callback) callback();
    }
}

    // 페이지 로드 후 뉴스 데이터 로딩 시작
    loadNewsData();


    // 사이드바 관련 코드
    const $sidebar = $('.sidebar');
    const $container = $('.container');
    const $keywordItems = $('.keyword-item');
    const $newsArticles = $('.stock-news');

    // 스크롤 이벤트 리스너
    $(window).scroll(highlightKeyword);

    // 키워드 클릭 이벤트 리스너
    $keywordItems.click(function() {
        const keyword = $(this).text().trim();
        const $targetArticle = $newsArticles.filter(function() {
            return $(this).find('.stock-name').text().trim() === keyword;
        });
        if ($targetArticle.length) {
            $('html, body').animate({
                scrollTop: $targetArticle.offset().top - 30
            }, 500);
        }
    });

    // 현재 보이는 뉴스에 해당하는 키워드 강조
    function highlightKeyword() {
        let $currentArticle = null;
        $newsArticles.each(function() {
            const rect = this.getBoundingClientRect();
            if (rect.top <= 100 && rect.bottom >= 100) {
                $currentArticle = $(this);
                return false;
            }
        });

        if ($currentArticle) {
            const keyword = $currentArticle.find('.stock-name').text().trim();
            $keywordItems.removeClass('active').filter(function() {
                return $(this).text().trim() === keyword;
            }).addClass('active');
        }
    }

    // 초기 키워드 강조
    highlightKeyword();

    // 링크 클릭 로깅
    $('a').click(function(e) {
        console.log('Link clicked');
        $.ajax({
            url: '/log_click',
            method: 'POST',
            contentType: 'application/json',
            headers: {
                'X-CSRFToken': csrfToken
            },
            data: JSON.stringify({
                clicked: true
            }),
            success: function(data) {
                console.log('Server response:', data);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.error('Error:', textStatus, errorThrown);
            }
        });
    });
});
</script>
</body>
<footer>
    <p class="investor-info">
        <small>
            화면에 표시된 시세는 실제 시세와 시간 차이가 있을 수 있습니다. 
            <br>이로 인한 투자 결과의 책임은 투자자 개인에게 있습니다.
            <br>실제 매매시에는 반드시 정확한 정보를 확인하시기 바랍니다.
        </small>
    </p>
    <a href="https://forms.gle/TiDdZ9MbpBaC7tQ79" id="contact-footer">
        <p class="contact-info">
            <small>
                문의하기
            </small>
        </p>
    </a>
</footer>
</html>

leadliner/templates/landing.html
<!DOCTYPE html>
<html lang="ko">
<head>
        <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5Z4CN57J');</script>
    <!-- End Google Tag Manager -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keyword" content="맞춤 뉴스, 개인화 뉴스, 뉴스 추천, 뉴스 큐레이션, 주식 뉴스, 경제 뉴스, 테크 뉴스">
    <meta name="description" content="내 보유 주식 뉴스만 모아보고 싶다면? 관심 있는 키워드만 선택하면 관련 뉴스만 쏙쏙! 시간 낭비 없는 개인화 맞춤 뉴스 서비스, 리드라이너에서 시작하세요.">
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4CJFS0TXDQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4CJFS0TXDQ');
</script>
    <title>리드라이너 - 나만의 주식 뉴스 브리핑</title>
    <link rel="stylesheet" href="../static/css/landing_style.css">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/maru-buri.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="logo-container">
        <img src="../static/assets/logo(white).png" alt="리드라이너 로고" class="logo" id="floating-logo">
    </div>
    <div class="landing-section">
        <div class="background-slideshow"></div>
        <div class="background-overlay"></div>
        <div class="container">
            <main>
                <section class="hero">
                    <h1>나만의 AI 주식 비서</h1>
                    <p>매일 내 주식 뉴스만 모아서 요약해주는 <br> AI 주식 비서의 브리핑을 받아보세요.</p>
                    <div class="cta-buttons">
                        <a href="{{ url_for('auth.signup') }}" class="btn btn-signup">회원가입</a>
                        <a href="{{ url_for('auth.login') }}" class="btn btn-login">로그인</a>
                    </div>
                </section>
            </main>
        </div>
        <div class="scroll-indicator">
            <i class="fas fa-chevron-down"></i>
        </div>
    </div>
    <section class="description">
        <div class="description-content">
            <img src="../static/assets/logo(black).png" alt="리드라이너 로고" class="logo description-logo" id="description-logo">
            <div class="character-section character-w">
                <img src="../static/assets/character_w.jpg" alt="여성 캐릭터" class="character-img">
                <div class="character-text">
                    <p>리드라이너는 AI 기술을 활용하여 개인화된 주식 뉴스 요약 서비스를 제공합니다.</p>
                    <p>매일 여러분이 관심 있는 주식 종목의 최신 뉴스를 분석하고 요약하여 제공합니다.</p>
                </div>
            </div>
            <div class="character-section character-m">
                <div class="character-text">
                    <p>여러 곳에 흩어져 있는 뉴스를 한 번에 볼 수 있어요!</p>
                    <p>리드라이너와 함께 효율적인 주식 투자를 시작해보세요!</p>
                </div>
                <img src="../static/assets/character_m.jpg" alt="남성 캐릭터" class="character-img">
            </div>
            <div class="cta-container">
                <a href="{{ url_for('auth.signup') }}" class="btn btn-signup">지금 시작하기</a>
            </div>
        </div>
    </section>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const backgroundElement = document.querySelector('.background-slideshow');
            const images = [
                "../static/assets/landing_page_image.jpg",
                "../static/assets/landing_page_image_2.jpg",
                "../static/assets/landing_page_image_3.jpg"
            ];
            let currentIndex = 0;

            function changeBackground() {
                backgroundElement.style.backgroundImage = `url('${images[currentIndex]}')`;
                currentIndex = (currentIndex + 1) % images.length;
            }

            // 초기 배경 설정
            changeBackground();

            // 10초마다 배경 변경
            setInterval(changeBackground, 10000);
        });

        document.addEventListener('DOMContentLoaded', function() {
    const floatingLogo = document.getElementById('floating-logo');
    const descriptionLogo = document.getElementById('description-logo');
    const descriptionSection = document.querySelector('.description');

    window.addEventListener('scroll', function() {
        const descriptionTop = descriptionSection.getBoundingClientRect().top;
        const windowHeight = window.innerHeight;

        if (descriptionTop <= windowHeight / 2) {
            floatingLogo.style.opacity = '0';
            descriptionLogo.style.display = 'inline-block';
        } else {
            floatingLogo.style.opacity = '1';
            descriptionLogo.style.display = 'none';
        }

        if (descriptionTop <= 0) {
            floatingLogo.style.display = 'none';
        } else {
            floatingLogo.style.display = 'inline-block';
        }
    });
});
    </script>
</body>
</html>